//postActions
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const ADD_SERVICES = "ADD_SERVICES";
export const ADD_PROJECT = "ADD_PROJECT";
export const CHANGE_LOADING_PROJECTS = "CHANGE_LOADING_PROJECTS";
export const CHANGE_LOADING_SERVICES = "CHANGE_LOADING_SERVICES";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_PROJECTS = "DELETE_PROJECTS";
export const DELETE_SERVICE = "DELETE_SERVICE";

//authActions
export const CHANGE_LOGGED_USER = "CHANGE_LOGGED_USER";

//general
export const HTTP_ERROR = "HTTP_ERROR";